In [1]:
import pandas as pd

In [8]:
# Combine all skills
ntu_data = pd.read_csv("../../Data/university_courses/NTU_course_info.csv")
ntu_data['mod_desc'] = ntu_data['Course Aims'] + " " + ntu_data["Intended Learning Outcomes"] + " " + ntu_data["Course Contents"]
ntu_data['mod_desc'] = ntu_data['mod_desc'].replace('\n',"")
ntu_data = ntu_data.dropna(how='all', axis='columns')
ntu_data

KeyError: 'Course Aims'

In [6]:
ntu_data.to_csv('../../Data/university_courses/NTU_course_info.csv', index=False)

In [19]:
sutd_data = pd.read_csv("../../Data/university_courses/SUTD_course_info.csv")
sutd_data

,Module code,Module Title,Module Category,Module level,Department,Workload,Preclusion,Prerequisites,Semester offered,Module description,Final,Project,URL Link,Topic covered,Module feedback,Learning Objective,Measurable Outcomes,Project.1,Final.1,mod_desc
0,10.014,Computational Thinking for Design,Computer Science,NaN,Faculty of Architecture and Sustainable Design...,12.0,NaN,NaN,NaN,An introductory programming course that combin...,NaN,NaN,NaN,NaN,NaN,Acquire conceptual knowledge and skills for vi...,Implement a working visual/textual program to ...,1.0,0.0,An introductory programming course that combin...
1,50.001,Information Systems & Programming,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design (For ...,NaN,This course is an introduction to the design a...,NaN,NaN,NaN,"Java Introduction, Android Studio, Array, Stri...",NaN,Identify and describe the requirements for an ...,Apply the key concepts of Object Oriented Prog...,1.0,1.0,This course is an introduction to the design a...
2,50.002,Computation Structures,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design (For ...,NaN,This course introduces architecture of digital...,NaN,NaN,NaN,"Course overview and mechanics, Basics of Infor...",NaN,State the role of abstraction in the design of...,Identify flaws and limitations in simple syste...,1.0,1.0,This course introduces architecture of digital...
3,50.003,Elements of Software Construction,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.001 Information Systems & Programming,NaN,This course is an introduction to the fundamen...,NaN,NaN,NaN,"Software Development Process, Software Design ...",NaN,Design medium-scale software system from scrat...,Build medium-scale software prototype (LO 1-5)...,1.0,1.0,This course is an introduction to the fundamen...
4,50.004,Algorithms,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design (For ...,NaN,This course is an introduction to algorithms a...,NaN,NaN,NaN,"Complexity, Asymptotic notation, Document dist...",NaN,"At the end of the term, students will be able ...",Compute the asymptotic complexity of algorithm...,1.0,1.0,This course is an introduction to algorithms a...
5,50.005,Computer System Engineering,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.002 Computation Structures,NaN,Topics on the engineering of computing and net...,NaN,NaN,NaN,Key challenges and basic principles in the des...,NaN,"At the end of the term, students will be able ...","Use software tools to understand, measure, and...",1.0,1.0,Topics on the engineering of computing and net...
6,50.007,Machine Learning,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.001 Information Systems & Programming and 5...,NaN,Machine learning is the study of algorithms th...,NaN,NaN,NaN,Introduction\nPerceptron\nLinear Regression\nL...,NaN,"At the end of the term, students will be able ...",List useful real-world applications of machine...,1.0,1.0,Machine learning is the study of algorithms th...
7,40.319,Statistical and Machine Learning,Data Science,NaN,Faculty of Engineering Systems and Design,12.0,NaN,40.017 Probability and Statistics,NaN,An agent is intelligent if it perceives its en...,NaN,NaN,NaN,NaN,NaN,Acquire a basic understanding in the fundament...,Design suitable mathematical models for real-w...,1.0,1.0,An agent is intelligent if it perceives its en...
8,50.038,Computational Data Science,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design (For ...,NaN,This course provides students the necessary ba...,NaN,NaN,NaN,"Intro DS and Hadoop, Features + Text, Visualis...",NaN,"Be aware of the main goals of data science, it...",Identify important concepts and current challe...,1.0,1.0,This course provides students the necessary ba...
9,50.043,Database Systems,"Computer Science, Data Science",NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design (For ...,NaN,Database systems manage data which is at the h...,NaN,NaN,NaN,"Database systems internal, Relational model, E...",NaN,Design and implement a database application on...,Develop a database design for an application.\...,1.0,1.0,Database systems manage data which is at the h...
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
11,50.035,Computer Vision,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.007 Machine Learning/ 40.319 Statistical & ...,NaN,This is an advanced undergraduate level course...,NaN,NaN,NaN,"Image, Filtering, Convolution, Image Histogram...",NaN,List useful real-world applications of compute...,Design image convolution and filtering using O...,1.0,1.0,This is an advanced undergraduate level course...
12,50.039,Theory and Practice of Deep Learning,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.007 Machine Learning and ability to to code...,NaN,The course goal is to familiarize students wit...,NaN,NaN,NaN,"Introduction, Review of ML, Syntactic Tagging,...",NaN,"By the end of the course, students will be abl...",Evaluate deep learning models and loss functio...,1.0,1.0,The course goal is to familiarize students wit...
13,50.040,Natural Language Processing,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.007 Machine Learning/40.319 Statistical & M...,NaN,Natural Language Processing (NLP) is an import...,NaN,NaN,NaN,"Introduction, Review of ML, Syntactic Tagging,...",NaN,"By the end of the course, students will be abl...",Explain the major tasks within NLP that involv...,1.0,1.0,Natural Language Processing (NLP) is an import...
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,50.006,User Interface Design and Implementation,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.009 The Digital World (For AY2019) or 10.01...,NaN,The course will introduce the field of Human-C...,NaN,NaN,NaN,"User classification and user centred design, I...",NaN,"Understand the concept of usability, design pr...","Apply design principles, guidelines and heuris...",1.0,1.0,The course will introduce the field of Human-C...
16,50.012,Networks,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.005 Computer System Engineering or\nA worki...,NaN,This course will introduce the principles and ...,NaN,NaN,NaN,"Computer Networks and the Internet, Applicatio...",NaN,Explain fundamental network protocols.\nDescri...,Description of the essential features of diffe...,1.0,1.0,This course will introduce the principles and ...
17,50.017,Graphics and Visualisation,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.003 Elements of Software Construction or kn...,NaN,"Introduction to computer graphics algorithms, ...",NaN,NaN,NaN,"Bezier Curve, Curve and Surface, Coordinates &...",NaN,Understand the fundamentals of computer graphi...,Understand key topics related to computer grap...,1.0,1.0,"Introduction to computer graphics algorithms, ..."
18,50.020,Network Security,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.042 Foundations of Cybersecurity,NaN,This course covers theory and practice of netw...,NaN,NaN,NaN,"Network protocol and the OSI model, Packet sni...",NaN,Explain common attacks and countermeasures in ...,"By the end of the course, students will be abl...",1.0,1.0,This course covers theory and practice of netw...
19,50.021,Artificial Intelligence,Data Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.007 Machine Learning/ 40.319 Statistical & ...,NaN,Artificial intelligence (AI) is a rich field s...,NaN,NaN,NaN,"Introduction to Artificial Intelligence, Searc...",NaN,"By the end of the course, students will be abl...",List current useful real-world applications of...,1.0,1.0,Artificial intelligence (AI) is a rich field s...
20,50.033,Foundations of Game Design and Development,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.001 Information Systems & Programming\n50.0...,NaN,This is an introductory course about the basic...,NaN,NaN,NaN,"Introduction, Game theory, challenges, and str...",NaN,Have a board but general overview of different...,Produce simple games with student’s novel idea...,1.0,1.0,This is an introductory course about the basic...
21,50.037,Blockchain Technology,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,The course assumes a basic familiarity with co...,NaN,"Decentralized blockchain-based systems, such a...",NaN,NaN,NaN,"Intro to Cryptographic Tools, Distributed Syst...",NaN,"By the end of the course, students will be abl...",Explain design principles of Bitcoin and Ether...,1.0,1.0,"Decentralized blockchain-based systems, such a..."
22,50.041,Distributed Systems and Computing,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.004 Algorithms or consultation with the ins...,NaN,This course introduces fundamental concepts fo...,NaN,NaN,NaN,"Introduction, Clocks, Election, Clocks and Ele...",NaN,Design and implement a distributed system from...,Build models of distributed systems [LO 1].\nP...,1.0,1.0,This course introduces fundamental concepts fo...
23,50.042,Foundations of Cybersecurity,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,NaN,NaN,This course provides students with a basic app...,NaN,NaN,NaN,"Introduction, Hash Functions, Password and Rai...",NaN,List basic security solutions and models; expl...,Evaluate security models like CIA model (confi...,1.0,1.0,This course provides students with a basic app...
24,50.044,System Security,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.042 Foundations of Cybersecurity,NaN,"This course covers the security of users, indi...",NaN,NaN,NaN,"Introduction, Memory safety attacks, Defenses ...",NaN,Define security objectives for a given compute...,Identify the security objectives of a computer...,1.0,1.0,"This course covers the security of users, indi..."
25,50.045,Information Retrieval,"Computer Science, Data Science",NaN,Faculty of Information Systems Technology and ...,12.0,NaN,Prior knowledge of elementary linear algebra w...,NaN,Automatic methods of Information Retrieval (IR...,NaN,NaN,NaN,"Boolean retrieval and VSM, Word Embeddings, Pr...",NaN,Gain knowledge about the basic concepts and te...,Identifying important concepts of Information ...,1.0,1.0,Automatic methods of Information Retrieval (IR...
26,50.046,Cloud Computing and Internet of Things,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.009 The Digital World (For Intake AY2019)\n...,NaN,The Internet of Things and its integration wit...,NaN,NaN,NaN,"Sensors, Embedded systems and RTOS, Wireless n...",NaN,To understand the related architecture designs...,List the functions of different IoT and cloud ...,1.0,1.0,The Internet of Things and its integration wit...
27,50.049,Parallel Computing on Multicore Architectures,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.004 Algorithms. Knowledge of Java/C program...,NaN,This course hence aims to equip students with ...,NaN,NaN,NaN,The overall module contains three parts.\n\nTh...,NaN,"Explain the key technologies (e.g., pipeline, ...",Able to understand the fundamental concepts of...,1.0,1.0,This course hence aims to equip students with ...
28,50.050,Discrete Mathematics and Algorithm Design,"Mathematics, Computer Science",NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.004 Algorithms\n10.018 Modelling Space and ...,NaN,An in-depth understanding of Computer Science ...,NaN,NaN,NaN,"Sets, set relations, bijections, cardinality a...",NaN,"At the end of the term, students will be able ...",Solve counting problems via multiple counting ...,1.0,1.0,An in-depth understanding of Computer Science ...
29,50.051,Programming Language Concepts,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,10.014 Computational Thinking for Design,NaN,"In this module, students will learn about data...",NaN,NaN,NaN,"Binary Operations, Data Representation, C prog...",NaN,Program in C and C++\nDesign a compiler for an...,Understand how memory is used to store data an...,1.0,1.0,"In this module, students will learn about data..."
30,50.052,Extended Reality,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.001 Information Systems & Programming or de...,NaN,Extended Reality (XR) encapsulates various imm...,NaN,NaN,NaN,"XR concept, Relation and difference between VR...",NaN,Define and explain the fundamental concepts in...,"By the end of this course, students should be ...",1.0,1.0,Extended Reality (XR) encapsulates various imm...
31,50.053,Software Testing and Verification,Computer Science,NaN,Faculty of Information Systems Technology and ...,12.0,NaN,50.003 Elements of Software Construction or go...,NaN,The course will introduce the fundamental conc...,NaN,NaN,NaN,"Dependency analysis, Slicing and data flow ana...",NaN,Design and implement software test generation ...,Build test generation techniques for complex s...,1.0,1.0,The course will introduce the fundamental conc...

In [17]:
sit_data = pd.read_csv("../../Data/university_courses/SIT_Module_Info.csv")
sit_data['mod_desc'] = sit_data['Module Description '] + " " + sit_data["Topics"]
sit_data.to_csv('../../Data/university_courses/SIT_Module_Info.csv', index=False)

In [319]:
# Store results in results dataframe
data = {'school' : ['NUS', "NTU", "SMU", "SUSS", "SUTD", "SIT"]}
results = pd.DataFrame(data)

# Read and Clean All Uni Module Info
nus_data = pd.read_csv("../../Data/university_courses/nus_dsa_mods.csv")
nus_data = nus_data.rename(columns = {'mod_category' : 'mod_cat', 'mod_exam' : 'mod_finals'})

ntu_data = pd.read_csv("../../Data/university_courses/NTU_course_info.csv")
ntu_data['mod_desc'] = ntu_data['Course Aims'] + " " + ntu_data["Intended Learning Outcomes"] + " " + ntu_data["Course Contents"]
ntu_data['mod_dept'] = ntu_data['Module Code'].astype(str).str[0:2]
ntu_data = ntu_data.rename(columns = {'Module Code' : 'mod_code', 'Module Name' : 'mod_name', 'Department' : 'mod_cat', 'Module Level' : 'mod_level', 'Pre-requisites': 'mod_prereq', 'Project': 'mod_proj', 'Final Exam' : 'mod_finals', 'Link' : 'mod_link'})
ntu_data = ntu_data.dropna(how='all', axis='columns')

smu_data = pd.read_csv("../../Data/university_courses/SMU_course_info.csv", skiprows = [0])
smu_data = smu_data.rename(columns = {'Module Code' : 'mod_code', 'Module Name' : 'mod_name', 'Department' : 'mod_dept', 'Module Level' : 'mod_level', 'Project': 'mod_proj', 'Final Exam' : 'mod_finals', 'Link' : 'mod_link', 'Module Category' : 'mod_cat', 'Description' : 'mod_desc'})

suss_data = pd.read_csv("../../Data/university_courses/SUSS_course_info.csv")
suss_data = suss_data.rename(columns = {'module code' : 'mod_code', 'module name' : 'mod_name', 'faculty' : 'mod_dept', 'level' : 'mod_level', 'prerequisites': 'mod_prereq', 'project ': 'mod_proj', 'final' : 'mod_finals', 'Link' : 'mod_link', 'module category' : 'mod_cat'})
cols = ['mod_finals', 'mod_proj']
suss_data[cols] = suss_data[cols].replace('T',1)
suss_data[cols] = suss_data[cols].replace('F',0)

sutd_data = pd.read_csv("../../Data/university_courses/SUTD_course_info.csv", skiprows = [0,1,2,3,4])
sutd_data['mod_desc'] = sutd_data['Module description'] + " " + sutd_data["Learning Objective"] + " " + sutd_data["Measurable Outcomes"]
sutd_data = sutd_data.rename(columns = {'Module code' : 'mod_code', 'Module Title' : 'mod_name', 'Department' : 'mod_dept', 'Prerequisites': 'mod_prereq', 'Project.1': 'mod_proj', 'Final.1' : 'mod_finals', 'Link' : 'mod_link', 'Module Category' : 'mod_cat', 'Module level' : 'mod_level', 'Preclusion' : 'mod_preclu'})
sutd_data = sutd_data.drop(columns = ['Final', 'Project'])

sit_data = pd.read_csv("../../Data/university_courses/SIT_Module_Info.csv")
sit_data['mod_desc'] = sit_data['Module Description '] + " " + sit_data["Topics"]
sit_data = sit_data.rename(columns = {'Module Code' : 'mod_code', 'Module Title' : 'mod_name', 'Department ' : 'mod_dept', 'Project.1': 'mod_proj', 'Final.1' : 'mod_finals', 'Link' : 'mod_link', 'Module Category' : 'mod_cat', 'Module Level' : 'mod_level', 'Department' : 'mod_dept'})

all_data = [nus_data, ntu_data, smu_data, suss_data, sutd_data, sit_data]
suss_data

,mod_code,mod_name,mod_cat,mod_level,module type,mod_dept,credit units,mod_prereq,preclusions,mod_finals,mod_proj,area of interest,semester offered,module description
0,ACC202,Financial and Managerial Accounting,Other,2,compulsory,School of Business,5,NaN,ACC201,1,0,business administration,"1,2",ACC202 Financial and Managerial Accounting is ...
1,ANL201,Data Visualisation for Business,Data Analytics,2,compulsory,School of Business,5,"ANL101,BUS105",ANL315,0,1,business administration,2,ANL201 Data Visualisation for Business is desi...
2,ANL252,Python for Data Analytics,Data Analytics,2,compulsory,School of Business,5,NaN,ANL251,0,1,business administration,"1,2","ANL252 Python for Data Analytics, as part of t..."
3,ANL303,Fundamentals of Data Mining,Data Analytics,3,compulsory,School of Business,5,NaN,NaN,1,0,business administration,"1,2",Fundamentals of Data Mining (ANL303) introduce...
4,ANL305,Association and Clustering,Data Science,3,compulsory,School of Business,5,ANL303,NaN,1,0,business administration,1,ANL305 Association and Clustering equips stude...
5,ANL307,Predictive Modelling,Data Science,3,compulsory,School of Business,5,ANL303,NaN,1,0,business administration,2,ANL307 Predictive Modelling aims to equip stud...
6,ANL310,Business Analytics Applications and Issues,Data Analytics,3,compulsory,School of Business,5,ANL303,ANL309,1,1,business administration,2,ANL310 Business Analytics Applications and Iss...
7,ANL312,Text Mining and Applied Project Formulation,Data Science,3,compulsory,School of Business,5,ANL303,ANL311,0,1,business administration,1,ANL312 Text Mining and Applied Project Formula...
8,ANL488,Business Analytics Applied Project,Data Analytics,4,compulsory,School of Business,10,"ANL312,ANL201,ANL303,ANL305,ANL307,ANL310",ANL499,0,1,business administration,"1,2","With this project, students will apply the tec..."
9,BUS105,Statistics,Statistics,1,compulsory,School of Business,5,NaN,BSZ220,1,1,business administration,"1,2",This course provides students with an understa...
10,FIN203,Essentials of Financial Management,Other,2,compulsory,School of Business,5,NaN,"ECO201,BSZ221, DDZS2021",1,1,finance,"1,2",A business graduate needs to understand the es...
11,MKT202e,Marketing Management,Other,2,compulsory,School of Business,5,NaN,"BMSZ326,MKT201,MKT203",1,1,business administration,"1,2",MKT202 Marketing Management is designed to int...
12,ACC353,Accounting Analytics,Data Analytics,3,elective,School of Business,5,"ANL303,either (ACC201 and ACC202) or ACC202",NaN,1,1,business administration,1,ACC353 Accounting Analytics covers the applica...
13,ANL317,Business Forecasting,Data Science,3,compulsory,School of Business,5,BUS105,BUS103,1,1,business administration,2,ANL317 Business Forecasting equips students wi...
14,ANL321,Statistical Methods,Statistics,3,elective,School of Business,5,BUS105 or ANL101,ANL302,1,1,business administration,1,ANL321 Statistical Methods explores the mathem...
15,ANL351,SAS Programming and its Application,Data Analytics,3,elective,School of Business,5,ANL303e,NaN,1,1,business administration,1,ANL351 SAS Programming and its Application int...
16,ANL355,Applied Operations Research,Data Analytics,3,compulsory,NaN,5,BUS107,BUS362,1,1,NaN,2,ANL355 Applied Operations Research introduces ...
17,BIS388,Independent Study,"Data Science, Data Analytics",3,elective,NaN,5,passed more than 80cu of courses (excluding Uc...,NaN,0,1,NaN,"1,2",Independent Study is a one-semester course in ...
18,BME363,Applications of Artificial Intelligence in Hea...,Data Science,3,elective,School of Science & Technology,5,NaN,NaN,0,1,Science & Technology,1,BME363 introduces the concept of artificial in...
19,BUS102,Management in the Digital Age,Other,1,compulsory,School of Business,5,NaN,"BUS101,BSZ160",1,1,business administration,1,BUS102 Management in the Digital Age is an int...
20,BUS107,Quantitative Methods,"Computer Science, Mathematics",1,compulsory,School of Business,5,NaN,"BSZ220,BZS3001",1,1,business administration,"1,2",BUS107 Quantitative Methods introduces managem...
21,BUS201,Contract and Agency Law,Other,2,compulsory,School of Business,5,NaN,BSZ150,1,1,business administration,"1,2",BUS201 Contract & Agency Law introduces studen...
22,BUS352,Operations Analytics,Data Analytics,3,elective,School of Business,5,NaN,"BUS351,BSZ352",1,1,business administration,"1,2",Improvements in data-collecting technologies h...
23,BUS353,Project Management,Other,3,elective,School of Business,5,NaN,BSZ352 or BZS3002,0,1,business administration,"1,2",BUS353 Project Management will provide both th...
24,BUS357,Starting and Managing a business,Other,3,elective,School of Business,5,NaN,BFSZ333,0,1,business administration,"1,2",BUS357 Starting and Managing a Business provid...
25,ECO202,Economic Ideas and Models for Business,Other,2,compulsory,School of Business,5,NaN,"ECO201,BSZ221,DDZS2021",1,1,business administration,"1,2",ECO202 Economic Ideas and Models for Business ...
26,ENG233,Internet of Things (IoT),Computer Science,2,elective,School of Science & Technology,5,NaN,ENG303,0,1,Science & Technology,"1,2",ENG233 Internet of Things (IoT) introduces the...
27,ICT233,Data Programming,Computer Science,2,elective,School of Science & Technology,5,ICT133 or ANL252,ICT203,0,1,Science & Technology,"1,2",This course introduces students to the languag...
28,ICT330,Database Management Systems,Computer Science,3,elective,School of Science & Technology,5,NaN,ICT321,1,0,Science & Technology,"1,2",ICT330 Database Management Systems introduces ...
29,MKT365,Social Media Metrics & Analytics,Data Analytics,3,elective,School of Business,5,NaN,NaN,0,1,business administration,"1,2",The objective of MKT365 Social Media Metrics &...
30,MKT371,Customer Insights and Analytics,Data Analytics,3,elective,School of Business,5,NaN,MKT355,0,1,business administration,2,MKT371 Customer Insights and Analytics aims to...
31,MKT390,Marketing Research,Other,3,elective,School of Business,5,NaN,BMSZ321,1,1,business administration,2,Marketing research is considered one of the ke...

# Number of Modules Provided by School

Count Num of Rows

In [320]:
num_of_mods = []
for d in all_data:
    num_of_mods.append(len(d))
results['num_of_mods'] = num_of_mods
results

  school  num_of_mods
0    NUS           45
1    NTU           27
2    SMU           24
3   SUSS           32
4   SUTD           32
5    SIT           26

# Breakdown of Modules Offered By Departments

Group By Module Departments, Count Number of Modules

In [321]:
mod_depts = []
for df in all_data:
    mod_depts.append(df['mod_dept'].value_counts().to_dict())
results['mod_depts'] = mod_depts
results

  school  num_of_mods                                          mod_depts
0    NUS           45           {'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}
1    NTU           27  {'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...
2    SMU           24  {'School of Economics': 10, 'School of Computi...
3   SUSS           32  {'School of Business': 26, 'School of Science ...
4   SUTD           32  {'Faculty of Information Systems Technology an...
5    SIT           26          {'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}

# Breakdown of Module Levels

Group by module levels, count

In [322]:

mod_levels = []
for df in all_data:
    mod_levels.append(df['mod_level'].value_counts().to_dict())
results['mod_levels'] = mod_levels
results

,school,num_of_mods,mod_depts,mod_levels
0,NUS,45,"{'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}","{4: 20, 3: 14, 2: 8, 1: 2, 5: 1}"
1,NTU,27,"{'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...","{1: 13, 2: 7, 3: 4, 4: 3}"
2,SMU,24,"{'School of Economics': 10, 'School of Computi...","{4: 8, 2: 7, 3: 5, 1: 4}"
3,SUSS,32,"{'School of Business': 26, 'School of Science ...","{3: 19, 2: 9, 1: 3, 4: 1}"
4,SUTD,32,{'Faculty of Information Systems Technology an...,{}
5,SIT,26,"{'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}","{1.0: 8, 3.0: 6, 2.0: 4, 4.0: 2}"

# Overall Breakdown of Module Project & Finals

weighted proj-finals breakdown for each module e.g. for a module, proj and finals = 1, weighted proj and finals = 0.5 each

for a school, overall proj proportion = (sum of weighted proj score) / (sum of weighted proj score + sum of weighted finals score)

vice versa for overall finals proportion

In [323]:
mod_proj_finals = []
for df in all_data:
    if 'mod_finals' and 'mod_proj' in df.columns:
        df.loc[(df['mod_finals'] == 1) & (df['mod_proj'] == 1), ['mod_finals', 'mod_proj']] = 0.5
        num_of_finals = df['mod_finals'].sum()
        num_of_proj = df['mod_proj'].sum()
        total_num = num_of_finals + num_of_proj
        mod_proj_finals.append({'finals' : num_of_finals / total_num * 100, 'proj' : num_of_proj / total_num * 100})
    else:
        mod_proj_finals.append({})
results['mod_proj_finals'] = mod_proj_finals
results

,school,num_of_mods,mod_depts,mod_levels,mod_proj_finals
0,NUS,45,"{'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}","{4: 20, 3: 14, 2: 8, 1: 2, 5: 1}","{'finals': 51.11111111111111, 'proj': 48.88888..."
1,NTU,27,"{'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...","{1: 13, 2: 7, 3: 4, 4: 3}","{'finals': 62.96296296296296, 'proj': 37.03703..."
2,SMU,24,"{'School of Economics': 10, 'School of Computi...","{4: 8, 2: 7, 3: 5, 1: 4}","{'finals': 63.63636363636363, 'proj': 36.36363..."
3,SUSS,32,"{'School of Business': 26, 'School of Science ...","{3: 19, 2: 9, 1: 3, 4: 1}","{'finals': 39.0625, 'proj': 60.9375}"
4,SUTD,32,{'Faculty of Information Systems Technology an...,{},"{'finals': 48.38709677419355, 'proj': 51.61290..."
5,SIT,26,"{'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}","{1.0: 8, 3.0: 6, 2.0: 4, 4.0: 2}",{}

# Breakdown of Module Categories

In [324]:
mod_cats = []
for df in all_data:
    old = df['mod_cat'].value_counts().to_dict()
    new = {}
    for key in list(old.keys()):
        if ',' in key:
            cats = list(key.split(', '))
            for c in cats:
                if c in new:
                    new[c] += 0.5 * old[key]
                else:
                    new[c] = 0.5 * old[key]
        else:
            if key in new:
                new[key] += old[key]
            else:
                new[key] = old[key]

    mod_cats.append(new)
    
results['mod_cats'] = mod_cats
results

,school,num_of_mods,mod_depts,mod_levels,mod_proj_finals,mod_cats
0,NUS,45,"{'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}","{4: 20, 3: 14, 2: 8, 1: 2, 5: 1}","{'finals': 51.11111111111111, 'proj': 48.88888...","{'Statistics': 12.5, 'Data Science': 12.0, 'Ma..."
1,NTU,27,"{'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...","{1: 13, 2: 7, 3: 4, 4: 3}","{'finals': 62.96296296296296, 'proj': 37.03703...","{'Other': 8, 'Computer Science': 6, 'Mathemati..."
2,SMU,24,"{'School of Economics': 10, 'School of Computi...","{4: 8, 2: 7, 3: 5, 1: 4}","{'finals': 63.63636363636363, 'proj': 36.36363...","{'Data Analytics': 12.5, 'Data Science': 5.5, ..."
3,SUSS,32,"{'School of Business': 26, 'School of Science ...","{3: 19, 2: 9, 1: 3, 4: 1}","{'finals': 39.0625, 'proj': 60.9375}","{'Data Analytics': 11.5, 'Other': 9, 'Data Sci..."
4,SUTD,32,{'Faculty of Information Systems Technology an...,{},"{'finals': 48.38709677419355, 'proj': 51.61290...","{'Computer Science': 21.5, 'Data Science': 8.0..."
5,SIT,26,"{'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}","{1.0: 8, 3.0: 6, 2.0: 4, 4.0: 2}",{},"{'Computer Science': 10.5, 'Data Science': 7.0..."

# Breakdown of Modules in Each Category

In [325]:
mods_in_cat = []
for df in all_data:
    df = df.groupby(['mod_cat'])['mod_name'].apply(list).reset_index(name = 'mod_names_in_cat')
    old = df.set_index('mod_cat').T.to_dict('records')[0]
    new = {}
    for key in list(old.keys()):
        if ',' in key:
            cats = list(key.split(', '))
            for c in cats:
                if c in new:
                    new[c].extend(old[key])
                else:
                    new[c] = old[key]
        else:
            if key in new:
                new[key].extend(old[key])
            else:
                new[key] = old[key]

    mods_in_cat.append(new)
results['mods_in_cat'] = mods_in_cat
results

,school,num_of_mods,mod_depts,mod_levels,mod_proj_finals,mod_cats,mods_in_cat
0,NUS,45,"{'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}","{4: 20, 3: 14, 2: 8, 1: 2, 5: 1}","{'finals': 51.11111111111111, 'proj': 48.88888...","{'Statistics': 12.5, 'Data Science': 12.0, 'Ma...",{'Computer Science': ['Programming Methodology...
1,NTU,27,"{'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...","{1: 13, 2: 7, 3: 4, 4: 3}","{'finals': 62.96296296296296, 'proj': 37.03703...","{'Other': 8, 'Computer Science': 6, 'Mathemati...",{'Computer Science': ['Introduction to Computa...
2,SMU,24,"{'School of Economics': 10, 'School of Computi...","{4: 8, 2: 7, 3: 5, 1: 4}","{'finals': 63.63636363636363, 'proj': 36.36363...","{'Data Analytics': 12.5, 'Data Science': 5.5, ...",{'Computer Science': ['Business Data Managemen...
3,SUSS,32,"{'School of Business': 26, 'School of Science ...","{3: 19, 2: 9, 1: 3, 4: 1}","{'finals': 39.0625, 'proj': 60.9375}","{'Data Analytics': 11.5, 'Other': 9, 'Data Sci...",{'Computer Science': ['Internet of Things (IoT...
4,SUTD,32,{'Faculty of Information Systems Technology an...,{},"{'finals': 48.38709677419355, 'proj': 51.61290...","{'Computer Science': 21.5, 'Data Science': 8.0...",{'Computer Science': ['Computational Thinking ...
5,SIT,26,"{'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}","{1.0: 8, 3.0: 6, 2.0: 4, 4.0: 2}",{},"{'Computer Science': 10.5, 'Data Science': 7.0...",{'Computer Science': ['Introduction to Compute...

# Breakdown of Module Proj & Finals in Each Category

Group By Category
Compute Proj & Finals Proportion

In [326]:
proj_finals_in_cat = []
for df in all_data:
    if 'mod_finals' and 'mod_proj' in df.columns:
        df.loc[(df['mod_finals'] == 1) & (df['mod_proj'] == 1), ['mod_finals', 'mod_proj']] = 0.5
        df = df.groupby('mod_cat').agg({'mod_proj': 'sum', 'mod_finals' : 'sum'}).reset_index()
        old = df.set_index('mod_cat').T.to_dict()
        new = {}
        for key in list(old.keys()):
            if ',' in key:
                cats = list(key.split(', '))
                for c in cats:
                    if c in new:
                        new[c]['mod_proj'] += 0.5 * old[key]['mod_proj']
                        new[c]['mod_finals'] += 0.5 * old[key]['mod_finals']
                    else:
                        new[c] = {'mod_proj' : 0.5 * old[key]['mod_proj'], 'mod_finals' : 0.5 * old[key]['mod_finals']}
            else:
                if key in new:
                    new[key]['mod_proj'] += old[key]['mod_proj']
                    new[key]['mod_finals'] += old[key]['mod_finals']
                else:
                    new[key] = {'mod_proj' : old[key]['mod_proj'], 'mod_finals' : old[key]['mod_finals']}

    proj_finals_in_cat.append(new)
results['proj_finals_in_cat'] = proj_finals_in_cat
results

,school,num_of_mods,mod_depts,mod_levels,mod_proj_finals,mod_cats,mods_in_cat,proj_finals_in_cat
0,NUS,45,"{'CS': 14, 'DSA': 12, 'ST': 12, 'MA': 7}","{4: 20, 3: 14, 2: 8, 1: 2, 5: 1}","{'finals': 51.11111111111111, 'proj': 48.88888...","{'Statistics': 12.5, 'Data Science': 12.0, 'Ma...",{'Computer Science': ['Programming Methodology...,"{'Computer Science': {'mod_proj': 3.5, 'mod_fi..."
1,NTU,27,"{'CZ': 9, 'MH': 7, 'CC': 6, 'SC': 2, 'ML': 1, ...","{1: 13, 2: 7, 3: 4, 4: 3}","{'finals': 62.96296296296296, 'proj': 37.03703...","{'Other': 8, 'Computer Science': 6, 'Mathemati...",{'Computer Science': ['Introduction to Computa...,"{'Computer Science': {'mod_proj': 1.5, 'mod_fi..."
2,SMU,24,"{'School of Economics': 10, 'School of Computi...","{4: 8, 2: 7, 3: 5, 1: 4}","{'finals': 63.63636363636363, 'proj': 36.36363...","{'Data Analytics': 12.5, 'Data Science': 5.5, ...",{'Computer Science': ['Business Data Managemen...,"{'Computer Science': {'mod_proj': 0.5, 'mod_fi..."
3,SUSS,32,"{'School of Business': 26, 'School of Science ...","{3: 19, 2: 9, 1: 3, 4: 1}","{'finals': 39.0625, 'proj': 60.9375}","{'Data Analytics': 11.5, 'Other': 9, 'Data Sci...",{'Computer Science': ['Internet of Things (IoT...,"{'Computer Science': {'mod_proj': 2.25, 'mod_f..."
4,SUTD,32,{'Faculty of Information Systems Technology an...,{},"{'finals': 48.38709677419355, 'proj': 51.61290...","{'Computer Science': 21.5, 'Data Science': 8.0...",{'Computer Science': ['Computational Thinking ...,"{'Computer Science': {'mod_proj': 11.25, 'mod_..."
5,SIT,26,"{'CSC': 10, 'ICT': 8, 'DCM': 1, 'PHE': 1}","{1.0: 8, 3.0: 6, 2.0: 4, 4.0: 2}",{},"{'Computer Science': 10.5, 'Data Science': 7.0...",{'Computer Science': ['Introduction to Compute...,"{'Computer Science': {'mod_proj': 11.25, 'mod_..."

# Foundation of Each Category

Group By Category and Count mean(Number of each Pre-req of a module)? nus, ntu, suss, sutd

In [ ]:
found_of_cat = []
for df in all_data:
    df = df.groupby(['mod_cat'])['mod_name'].apply(list).reset_index(name = 'mod_names_in_cat')
    old = df.set_index('mod_cat').T.to_dict('records')[0]
    new = {}
    for key in list(old.keys()):
        if ',' in key:
            cats = list(key.split(', '))
            for c in cats:
                if c in new:
                    new[c].extend(old[key])
                else:
                    new[c] = old[key]
        else:
            if key in new:
                new[key].extend(old[key])
            else:
                new[key] = old[key]

    found_of_cat.append(new)
results['found_of_cat'] = found_of_cat
results

# Additional Ideas
**Alternatives for Each Category**

Group By Category and Count mean(Number of Pre-clusions) nus, suss

**Nature of Module: Compulsory or Elective**

nus (add), ntu, suss

# Import to Excel File

In [327]:
# results.to_excel(r"../../Data/salary_info.xlsx", sheet_name='Sheet3', index=False)
from openpyxl import load_workbook
book = load_workbook('../../Data/salary_info.xlsx')
writer = pd.ExcelWriter('../../Data/salary_info.xlsx', engine='openpyxl') 
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
results.to_excel(writer, "Sheet3")
writer.save()